trigger:
  branches:
    include:
      - main

pool:
  name: Default   # Self-hosted agent

variables:
  environment: dev
  dockerHubRepo: prasidsash/employeeprofileapp
  imageTag: $(Build.BuildId)

stages:

# ======================================================
# CI STAGE – BUILD AND PUSH IMAGE
# ======================================================

- stage: Build
  displayName: Build and Push Docker Image

  jobs:

  - job: BuildAndPush
    displayName: Docker Build and Push

    steps:

    - checkout: self

    - script: |
        echo =================================
        echo Starting CI Pipeline
        echo Environment = $(environment)
        echo Build ID = $(Build.BuildId)
        echo =================================
      displayName: Print Build Info

    - task: Docker@2
      displayName: Build and Push Image to Docker Hub
      inputs:
        containerRegistry: dockerhub-connection
        repository: $(dockerHubRepo)
        command: buildAndPush
        Dockerfile: Dockerfile
        tags: |
          $(imageTag)

# ======================================================
# CD STAGE – TERRAFORM INFRASTRUCTURE
# ======================================================

- stage: Terraform
  displayName: Provision Infrastructure
  dependsOn: Build

  jobs:

  - job: TerraformApply
    displayName: Terraform Apply

    steps:

    - checkout: self

    - powershell: |

        Write-Host "================================="
        Write-Host "Starting Terraform Deployment"
        Write-Host "Environment: $(environment)"
        Write-Host "================================="

        cd terraform/environments/$(environment)

        terraform init

        terraform plan -var-file="$(environment).tfvars"

        terraform apply -auto-approve -var-file="$(environment).tfvars"

      displayName: Terraform Apply


# ======================================================
# CD STAGE – HELM APPLICATION DEPLOYMENT
# ======================================================

- stage: Deploy
  displayName: Deploy Application with Helm
  dependsOn: Terraform

  jobs:

  - job: HelmDeploy
    displayName: Helm Upgrade / Install

    steps:

    - checkout: self

    - powershell: |

        Write-Host "================================="
        Write-Host "Starting Helm Deployment"
        Write-Host "Environment: $(environment)"
        Write-Host "Image Tag: $(imageTag)"
        Write-Host "================================="

        $namespace="employeeprofileapp-$(environment)"

        helm upgrade --install employeeprofileapp `
          helm/app-chart `
          --namespace $namespace `
          --create-namespace `
          -f helm/app-chart/values-$(environment).yaml `
          --set image.repository=$(dockerHubRepo) `
          --set image.tag=$(imageTag)

      displayName: Helm Upgrade