trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  dockerHubRepo: prasidsash/employeeprofileapp
  imageTag: $(Build.BuildId)

stages:

# ======================================================
# CI – BUILD IMAGE
# ======================================================

- stage: Build
  displayName: Build Docker Image

  jobs:

  - job: Build
    displayName: Build and Push

    steps:

    - checkout: self

    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        containerRegistry: dockerhub-connection
        repository: $(dockerHubRepo)
        command: buildAndPush
        Dockerfile: Dockerfile
        tags: |
          $(imageTag)

# ======================================================
# DEV DEPLOYMENT
# ======================================================

- stage: Deploy_Dev
  displayName: Deploy to DEV
  dependsOn: Build

  variables:
    environment: dev

  jobs:

  - job: DeployDev

    steps:

    - checkout: self

    - script: |
        cd terraform/environments/dev
        terraform init
        terraform apply -auto-approve -var-file="dev.tfvars"
      displayName: Terraform DEV

    - script: |
        helm upgrade --install employeeprofileapp \
        helm/app-chart \
        --namespace employeeprofileapp-dev \
        -f helm/app-chart/values-dev.yaml \
        --set image.repository=$(dockerHubRepo) \
        --set image.tag=$(imageTag)
      displayName: Helm DEV


# ======================================================
# QA DEPLOYMENT
# ======================================================

- stage: Deploy_QA
  displayName: Deploy to QA
  dependsOn: Deploy_Dev

  variables:
    environment: qa

  jobs:

  - job: DeployQA

    steps:

    - checkout: self

    - script: |
        cd terraform/environments/qa
        terraform init
        terraform apply -auto-approve -var-file="qa.tfvars"
      displayName: Terraform QA

    - script: |
        helm upgrade --install employeeprofileapp \
        helm/app-chart \
        --namespace employeeprofileapp-qa \
        -f helm/app-chart/values-qa.yaml \
        --set image.repository=$(dockerHubRepo) \
        --set image.tag=$(imageTag)
      displayName: Helm QA


# ======================================================
# UAT DEPLOYMENT
# ======================================================

- stage: Deploy_UAT
  displayName: Deploy to UAT
  dependsOn: Deploy_QA

  variables:
    environment: uat

  jobs:

  - job: DeployUAT

    steps:

    - checkout: self

    - script: |
        cd terraform/environments/uat
        terraform init
        terraform apply -auto-approve -var-file="uat.tfvars"
      displayName: Terraform UAT

    - script: |
        helm upgrade --install employeeprofileapp \
        helm/app-chart \
        --namespace employeeprofileapp-uat \
        -f helm/app-chart/values-uat.yaml \
        --set image.repository=$(dockerHubRepo) \
        --set image.tag=$(imageTag)
      displayName: Helm UAT


# ======================================================
# PROD DEPLOYMENT
# ======================================================

- stage: Deploy_Prod
  displayName: Deploy to PROD
  dependsOn: Deploy_UAT

  variables:
    environment: prod

  jobs:

  - job: DeployProd

    steps:

    - checkout: self

    - script: |
        cd terraform/environments/prod
        terraform init
        terraform apply -auto-approve -var-file="prod.tfvars"
      displayName: Terraform PROD

    - script: |
        helm upgrade --install employeeprofileapp \
        helm/app-chart \
        --namespace employeeprofileapp-prod \
        -f helm/app-chart/values-prod.yaml \
        --set image.repository=$(dockerHubRepo) \
        --set image.tag=$(imageTag)
      displayName: Helm PROD