trigger: none

resources:
  pipelines:
  - pipeline: ci
    source: azure-pipelines-ci
    trigger: true

pool:
  name: Default

variables:
  dockerHubRepo: prasidsash/employeeprofileapp

stages:

# ======================================================
# DEV DEPLOYMENT
# ======================================================

- stage: Deploy_DEV
  displayName: Deploy to DEV

  jobs:
  - deployment: DeployDev
    displayName: Helm Deploy DEV
    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - download: ci
            artifact: imageTag

          - powershell: |

              Write-Host "================================"
              Write-Host "Starting DEV Deployment"
              Write-Host "================================"

              $tag = Get-Content "$(Pipeline.Workspace)/ci/imageTag/imageTag.txt"

              Write-Host "Image Tag: $tag"

              kubectl config current-context
              kubectl get nodes

              $namespace="employeeprofileapp-dev"

              helm upgrade --install employeeprofileapp `
                ./helm/app-chart `
                --namespace $namespace `
                --create-namespace `
                -f ./helm/app-chart/values-dev.yaml `
                --set image.repository=$(dockerHubRepo) `
                --set image.tag=$tag

              kubectl rollout status deployment/employeeprofileapp-employeeprofileapp -n $namespace
              kubectl get pods -n $namespace


# ======================================================
# QA DEPLOYMENT
# ======================================================

- stage: Deploy_QA
  displayName: Deploy to QA
  dependsOn: Deploy_DEV

  jobs:
  - deployment: DeployQA
    displayName: Helm Deploy QA
    environment: qa

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - download: ci
            artifact: imageTag

          - powershell: |

              Write-Host "================================"
              Write-Host "Starting QA Deployment"
              Write-Host "================================"

              $tag = Get-Content "$(Pipeline.Workspace)/ci/imageTag/imageTag.txt"

              Write-Host "Image Tag: $tag"

              $namespace="employeeprofileapp-qa"

              helm upgrade --install employeeprofileapp `
                ./helm/app-chart `
                --namespace $namespace `
                --create-namespace `
                -f ./helm/app-chart/values-qa.yaml `
                --set image.repository=$(dockerHubRepo) `
                --set image.tag=$tag

              kubectl rollout status deployment/employeeprofileapp-employeeprofileapp -n $namespace
              kubectl get pods -n $namespace


# ======================================================
# UAT DEPLOYMENT
# ======================================================

- stage: Deploy_UAT
  displayName: Deploy to UAT
  dependsOn: Deploy_QA

  jobs:
  - deployment: DeployUAT
    displayName: Helm Deploy UAT
    environment: uat

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - download: ci
            artifact: imageTag

          - powershell: |

              Write-Host "================================"
              Write-Host "Starting UAT Deployment"
              Write-Host "================================"

              $tag = Get-Content "$(Pipeline.Workspace)/ci/imageTag/imageTag.txt"

              Write-Host "Image Tag: $tag"

              $namespace="employeeprofileapp-uat"

              helm upgrade --install employeeprofileapp `
                ./helm/app-chart `
                --namespace $namespace `
                --create-namespace `
                -f ./helm/app-chart/values-uat.yaml `
                --set image.repository=$(dockerHubRepo) `
                --set image.tag=$tag

              kubectl rollout status deployment/employeeprofileapp-employeeprofileapp -n $namespace
              kubectl get pods -n $namespace


# ======================================================
# PROD DEPLOYMENT
# ======================================================

- stage: Deploy_PROD
  displayName: Deploy to PROD
  dependsOn: Deploy_UAT

  jobs:
  - deployment: DeployProd
    displayName: Helm Deploy PROD
    environment: prod

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - download: ci
            artifact: imageTag

          - powershell: |

              Write-Host "================================"
              Write-Host "Starting PROD Deployment"
              Write-Host "================================"

              $tag = Get-Content "$(Pipeline.Workspace)/ci/imageTag/imageTag.txt"

              Write-Host "Image Tag: $tag"

              $namespace="employeeprofileapp-prod"

              helm upgrade --install employeeprofileapp `
                ./helm/app-chart `
                --namespace $namespace `
                --create-namespace `
                -f ./helm/app-chart/values-prod.yaml `
                --set image.repository=$(dockerHubRepo) `
                --set image.tag=$tag

              kubectl rollout status deployment/employeeprofileapp-employeeprofileapp -n $namespace
              kubectl get pods -n $namespace