sonar.projectKey=employeeprofileapp
sonar.projectName=EmployeeProfileApp
sonar.projectVersion=1.0

sonar.sources=src

sonar.host.url=http://localhost:9000

sonar.login=squ_efc2318a007d6f262465556309fa37d4cf4e25c9