apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employeeprofileapp.fullname" . }}
  labels:
    {{- include "employeeprofileapp.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      {{- include "employeeprofileapp.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "employeeprofileapp.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      containers:
        - name: {{ include "employeeprofileapp.name" . }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DB_PASSWORD

            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.environment }}"

            - name: APP_ENV
              value: "{{ .Values.environment }}"

          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3