{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "employeeprofileapp.fullname" . }}-ingress
  labels:
    {{- include "employeeprofileapp.labels" . | nindent 4 }}
spec:
  ingressClassName: traefik

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "employeeprofileapp.fullname" . }}
                port:
                  number: 80
{{- end }}