replicaCount: 1

image:
  repository: prasidsash/employeeprofileapp
  tag: ""                     # 👈 leave empty (pipeline will inject)
  pullPolicy: Always

service:
  type: NodePort              # 👈 REQUIRED
  port: 80
  targetPort: 8080            # 👈 must match your app
  nodePort: 30503

ingress:
  enabled: true

environment: prod