replicaCount: 3

image:
  repository: prasidsash/employeeprofileapp
  tag: 0
  pullPolicy: Always

service:
  nodePort: 30501

ingress:
  enabled: true

environment: qa

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 7
  cpu: 65