serviceAccount:
  name: employee-sa

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpu: 70

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  hosts: []

secret:
  name: employee-db-secret