serviceAccount:
  name: employee-sa

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: null         # 👈 add this

ingress:
  enabled: false
  className: nginx
  hosts: []

secret:
  name: employee-db-secret