replicaCount: 3

image:
  repository: prasidsash/employeeprofileapp
  tag: 0
  pullPolicy: Always

service:
  nodePort: 30502

ingress:
  enabled: true

environment: uat

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 8
  cpu: 65