replicaCount: 2

image:
  repository: employeeprofileapp
  tag: v2
  pullPolicy: IfNotPresent

serviceAccount:
  name: employee-sa

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  hosts: []

secret:
  name: employee-db-secret