replicaCount: 1

image:
  repository: prasidsash/employeeprofileapp
  tag: latest
  pullPolicy: Always

environment: dev

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: qa.employeeprofileapp.local